# Use the official Node.js runtime as the base image
FROM docker.arvancloud.ir/node:23-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
ENV REACT_APP_API_URL=http://localhost/api
# Install dependencies
RUN npm install

# Copy the entire application code to the container
COPY . .
# Build the React app for production
RUN npm run build

# Use Nginx as the production server
FROM docker.arvancloud.ir/nginx:alpine

# Copy the built React app to Nginx's web server directory
COPY --from=build /app/build /usr/share/nginx/html

# Copy the custom Nginx configuration file
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/ssl /etc/nginx/ssl

# Expose port 80 for the Nginx server
EXPOSE 80

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]