# Use the official Node.js runtime as the base image
FROM docker.arvancloud.ir/node:23 

# Set the working directory in the container
WORKDIR /app
RUN npm install -g pnpm
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
ENV REACT_APP_API_URL=http://localhost/api
# Install dependencies
RUN npm i

# Copy the entire application code to the container
COPY . .

CMD [ "npm" , "start" ]